// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RegisterUniversity(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RegisterUniversity'](arg1, arg2, arg3, arg4);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}
