// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RegisterUniversity(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Shutdown():Promise<string>;
