definitions:
  data.CertificateFileUpload:
    properties:
      dateOfIssuing:
        type: string
      encodedFile:
        type: string
      studentPublicKey:
        type: string
      universityName:
        type: string
    type: object
  data.CertificateOutput:
    properties:
      certHash:
        type: string
      certUUID:
        type: string
      dateOfIssuing:
        type: string
      studentPublicKey:
        type: string
      universityPublicKey:
        type: string
    type: object
  data.CertificateOutputFull:
    properties:
      base64File:
        type: string
      certHash:
        type: string
      certUUID:
        type: string
      dateOfIssuing:
        type: string
      studentPublicKey:
        type: string
      universityPublicKey:
        type: string
    type: object
  data.Country:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  data.QRInput:
    properties:
      certUUID:
        type: string
      studentPrivateKey:
        type: string
    type: object
  data.QROutput:
    properties:
      content:
        type: string
    type: object
  data.StudentAuth:
    properties:
      privateKey:
        type: string
    type: object
  data.StudentInput:
    properties:
      NIN:
        type: string
      countryID:
        type: integer
      dateOfBirth:
        type: string
      fullName:
        type: string
      password:
        type: string
    type: object
  data.StudentOutput:
    properties:
      fullName:
        type: string
      privateKey:
        type: string
      publicKey:
        type: string
    type: object
  data.UniversityInput:
    properties:
      description:
        type: string
      location:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  data.UniversityOutput:
    properties:
      name:
        type: string
      privateKey:
        type: string
      publicKey:
        type: string
    type: object
  gin.H:
    additionalProperties: {}
    type: object
info:
  contact: {}
paths:
  /api/countries:
    get:
      description: Get all countries
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.Country'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get all countries
      tags:
      - countries
  /api/countries/{id}:
    get:
      description: Get a country by ID
      parameters:
      - description: Country ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Country'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get a country by ID
      tags:
      - countries
  /api/qrs/create:
    post:
      consumes:
      - application/json
      description: Create a QR code
      parameters:
      - description: QR data
        in: body
        name: qr
        required: true
        schema:
          $ref: '#/definitions/data.QRInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/data.QROutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Create a QR code
      tags:
      - qrs
  /api/qrs/verify:
    post:
      consumes:
      - application/json
      description: Verify a QR code
      parameters:
      - description: QR token
        in: path
        name: qr
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: The file content in base64
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Verify a QR code
      tags:
      - qrs
  /api/students:
    post:
      consumes:
      - application/json
      description: Register a student
      parameters:
      - description: Student data
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/data.StudentInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/data.StudentOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Register a student
      tags:
      - students
  /api/students/certificates:
    post:
      consumes:
      - application/json
      description: Get all certificates of a student
      parameters:
      - description: Student data
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/data.StudentAuth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.CertificateOutput'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get all certificates of a student
      tags:
      - students
  /api/students/certificates/{certUUID}:
    post:
      consumes:
      - application/json
      description: Get one certificate of a student
      parameters:
      - description: Student data
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/data.StudentAuth'
      - description: Certificate UUID
        in: path
        name: certUUID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.CertificateOutputFull'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get one certificate of a student
      tags:
      - students
  /api/students/login:
    post:
      consumes:
      - application/json
      description: Login a student
      parameters:
      - description: Student data
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/data.StudentInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.StudentOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Login a student
      tags:
      - students
  /api/universities/certificate-file:
    post:
      consumes:
      - application/json
      description: Add a certificate file
      parameters:
      - description: Certificate file data
        in: body
        name: certificateFile
        required: true
        schema:
          $ref: '#/definitions/data.CertificateFileUpload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Add a certificate file
      tags:
      - universities
  /api/universities/register:
    post:
      consumes:
      - application/json
      description: Register a university
      parameters:
      - description: University registration data
        in: body
        name: university
        required: true
        schema:
          $ref: '#/definitions/data.UniversityInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/data.UniversityOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Register a university
      tags:
      - universities
swagger: "2.0"
