// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function GetAll() {
  return window['go']['main']['App']['GetAll']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitLedger() {
  return window['go']['main']['App']['InitLedger']();
}

export function IssueCertificate(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['IssueCertificate'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}
