#!/bin/bash

function createUET() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/uet/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/uet/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-uet --tls.certfiles "${PWD}/organizations/fabric-ca/uet/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-uet.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-uet.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-uet.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-uet.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/uet/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy uet's CA cert to uet's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/uet/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/uet/ca-cert.pem" "${PWD}/organizations/peerOrganizations/uet/msp/tlscacerts/ca.crt"

  # Copy uet's CA cert to uet's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/uet/tlsca"
  cp "${PWD}/organizations/fabric-ca/uet/ca-cert.pem" "${PWD}/organizations/peerOrganizations/uet/tlsca/tlsca.uet-cert.pem"

  # Copy uet's CA cert to uet's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/uet/ca"
  cp "${PWD}/organizations/fabric-ca/uet/ca-cert.pem" "${PWD}/organizations/peerOrganizations/uet/ca/ca.uet-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-uet --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/uet/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-uet --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/uet/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-uet --id.name uetadmin --id.secret uetadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/uet/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-uet -M "${PWD}/organizations/peerOrganizations/uet/peers/peer0.uet/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/uet/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/uet/msp/config.yaml" "${PWD}/organizations/peerOrganizations/uet/peers/peer0.uet/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-uet -M "${PWD}/organizations/peerOrganizations/uet/peers/peer0.uet/tls" --enrollment.profile tls --csr.hosts peer0.uet --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/uet/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/uet/peers/peer0.uet/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/uet/peers/peer0.uet/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/uet/peers/peer0.uet/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/uet/peers/peer0.uet/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/uet/peers/peer0.uet/tls/keystore/"* "${PWD}/organizations/peerOrganizations/uet/peers/peer0.uet/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-uet -M "${PWD}/organizations/peerOrganizations/uet/users/User1@uet/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/uet/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/uet/msp/config.yaml" "${PWD}/organizations/peerOrganizations/uet/users/User1@uet/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://uetadmin:uetadminpw@localhost:7054 --caname ca-uet -M "${PWD}/organizations/peerOrganizations/uet/users/Admin@uet/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/uet/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/uet/msp/config.yaml" "${PWD}/organizations/peerOrganizations/uet/users/Admin@uet/msp/config.yaml"
}

function createHUS() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/hus/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/hus/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-hus --tls.certfiles "${PWD}/organizations/fabric-ca/hus/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-hus.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-hus.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-hus.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-hus.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/hus/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy hus's CA cert to hus's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/hus/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/hus/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hus/msp/tlscacerts/ca.crt"

  # Copy hus's CA cert to hus's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hus/tlsca"
  cp "${PWD}/organizations/fabric-ca/hus/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hus/tlsca/tlsca.hus-cert.pem"

  # Copy hus's CA cert to hus's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hus/ca"
  cp "${PWD}/organizations/fabric-ca/hus/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hus/ca/ca.hus-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-hus --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/hus/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-hus --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/hus/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-hus --id.name husadmin --id.secret husadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/hus/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-hus -M "${PWD}/organizations/peerOrganizations/hus/peers/peer0.hus/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hus/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hus/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hus/peers/peer0.hus/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-hus -M "${PWD}/organizations/peerOrganizations/hus/peers/peer0.hus/tls" --enrollment.profile tls --csr.hosts peer0.hus --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/hus/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/hus/peers/peer0.hus/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/hus/peers/peer0.hus/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/hus/peers/peer0.hus/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/hus/peers/peer0.hus/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/hus/peers/peer0.hus/tls/keystore/"* "${PWD}/organizations/peerOrganizations/hus/peers/peer0.hus/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-hus -M "${PWD}/organizations/peerOrganizations/hus/users/User1@hus/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hus/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hus/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hus/users/User1@hus/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://husadmin:husadminpw@localhost:8054 --caname ca-hus -M "${PWD}/organizations/peerOrganizations/hus/users/Admin@hus/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hus/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hus/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hus/users/Admin@hus/msp/config.yaml"
}
function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/example

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/example

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/example/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example/msp/tlscacerts/tlsca.example-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example/tlsca/tlsca.example-cert.pem"

# Loop through each orderer (orderer, orderer2, orderer3, orderer4) to register and generate artifacts
  for ORDERER in orderer orderer2 orderer3 orderer4; do
    infoln "Registering ${ORDERER}"
    set -x
    fabric-ca-client register --caname ca-orderer --id.name ${ORDERER} --id.secret ${ORDERER}pw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Generating the ${ORDERER} MSP"
    set -x
    fabric-ca-client enroll -u https://${ORDERER}:${ORDERER}pw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example/orderers/${ORDERER}.example/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/ordererOrganizations/example/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example/orderers/${ORDERER}.example/msp/config.yaml"

    # Workaround: Rename the signcert file to ensure consistency with Cryptogen generated artifacts
    mv "${PWD}/organizations/ordererOrganizations/example/orderers/${ORDERER}.example/msp/signcerts/cert.pem" "${PWD}/organizations/ordererOrganizations/example/orderers/${ORDERER}.example/msp/signcerts/${ORDERER}.example-cert.pem"

    infoln "Generating the ${ORDERER} TLS certificates, use --csr.hosts to specify Subject Alternative Names"
    set -x
    fabric-ca-client enroll -u https://${ORDERER}:${ORDERER}pw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example/orderers/${ORDERER}.example/tls" --enrollment.profile tls --csr.hosts ${ORDERER}.example --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
    cp "${PWD}/organizations/ordererOrganizations/example/orderers/${ORDERER}.example/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example/orderers/${ORDERER}.example/tls/ca.crt"
    cp "${PWD}/organizations/ordererOrganizations/example/orderers/${ORDERER}.example/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/example/orderers/${ORDERER}.example/tls/server.crt"
    cp "${PWD}/organizations/ordererOrganizations/example/orderers/${ORDERER}.example/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/example/orderers/${ORDERER}.example/tls/server.key"

    # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
    mkdir -p "${PWD}/organizations/ordererOrganizations/example/orderers/${ORDERER}.example/msp/tlscacerts"
    cp "${PWD}/organizations/ordererOrganizations/example/orderers/${ORDERER}.example/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example/orderers/${ORDERER}.example/msp/tlscacerts/tlsca.example-cert.pem"
  done

  # Register and generate artifacts for the orderer admin
  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example/users/Admin@example/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example/users/Admin@example/msp/config.yaml"
}
